[build]
  base = "frontend/"
  publish = "build/"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "18"
  YARN_VERSION = "1.22.19"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NODE_ENV = "production"
  REACT_APP_SUPABASE_URL = "https://fcnenhbjrblxaihksbtr.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjbmVuaGJqcmJseGFpaGtzYnRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDMyODAsImV4cCI6MjA2NDI3OTI4MH0.VsZ9-b5TUvVU2sWdxHTzcr6PEzgAsSgM0-Ibb-ECpcc"
